version: "3.9"

networks:
  gmao-network:
  npm-network:
    external: true

volumes:
  pgdata:

services:
  db:
    image: postgres:15-alpine
    container_name: gmao-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D@n@kil31989
      POSTGRES_DB: gmao
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gmao-network
      - npm-network   # pour que d'autres conteneurs sur npm-network puissent y accéder

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: D@n@kil31989
        POSTGRES_DB: gmao
    env_file:
      - ./back/.env
    container_name: gmao-backend    
    environment:
      NODE_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D@n@kil31989
      POSTGRES_DB: gmao       
      POSTGRES_HOST: gmao-db   # important pour que le backend se connecte à la DB
    expose:
      - "3000"
    depends_on:
      - db
    networks:
      - gmao-network
      - npm-network

  frontend:
    build:
      context: .
      dockerfile: ./front/Dockerfile
      args:
        VITE_API_URL: "/api"
    container_name: gmao-frontend
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - gmao-network
      - npm-network

  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@domain.com
        PGADMIN_DEFAULT_PASSWORD: StrongPassword
      networks:
        - npm-network
      expose:
        - "5050"
