networks:
  gmao-network:
  npm-network:   # ðŸ‘ˆ ajout pour se brancher au rÃ©seau NPM
    external: true   # car dÃ©jÃ  crÃ©Ã© par Nginx Proxy Manager

volumes:
  pgdata:

services:
  db:
    image: postgres:15-alpine
    container_name: gmao-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D@n@kil31989
      POSTGRES_DB: gmao
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gmao-network   # ðŸ‘ˆ reste interne, pas exposÃ© Ã  NPM

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: D@n@kil31989
        POSTGRES_DB: gmao
    env_file:
      - ./back/.env
    container_name: gmao-backend    
    environment:
      NODE_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D@n@kil31989
      POSTGRES_DB: gmao       
    expose:         # ðŸ‘ˆ uniquement exposÃ© en interne
      - "3000"
    depends_on:
      - db
    networks:
      - gmao-network
      - npm-network   # ðŸ‘ˆ dispo dans NPM

  frontend:
    build:
      context: .
      dockerfile: ./front/Dockerfile
      args:
        VITE_API_URL: "/api"   # ðŸ‘ˆ proxy via nginx
    container_name: gmao-frontend
    expose:         # ðŸ‘ˆ exposÃ© au rÃ©seau interne
      - "80"
    depends_on:
      - backend
    networks:
      - gmao-network
      - npm-network   # ðŸ‘ˆ dispo dans NPM
