version: "3.9"

networks:
  gmao-network:
  npm-network:
    external: true

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: D@n@kil31989
        POSTGRES_DB: gmao
    env_file:
      - ./back/.env
    container_name: gmao-backend    
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      DATABASE_URL: postgresql://${EXTERNAL_DB_USER}:${EXTERNAL_DB_PASSWORD}@${EXTERNAL_DB_HOST}:${EXTERNAL_DB_PORT:-5432}/${EXTERNAL_DB_NAME}
      RESET_DATABASE: ${RESET_DATABASE:-false}
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    networks:
      - gmao-network
      - npm-network

  frontend:
    build:
      context: .
      dockerfile: ./front/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-/api}
    container_name: gmao-frontend
    ports:
      - "${FRONTEND_PORT:-5173}:80"
    depends_on:
      - backend
    networks:
      - gmao-network
      - npm-network

